Feat assignment1 mathutils
shafiq005-solin/CSharp-Assignments pull request #1
Opened 2023-08-14 12:39 UTC by shafiq005-solin

I have created a mathUtils class and it has four methods which will perform addition, subtraction, multiplication and division.
And I added two md files one is for exploration assignment and another one is about the programming. kindly review it and merge the branch. thank you : )
 
[Assignment1explore.md](https://github.com/shafiq005-solin/CSharp-Assignments/files/12334602/Assignment1explore.md)

2023-08-16 17:20 UTC, MithunSubramani commented on src/assignment1/MathUtils.cs
> +            return (long)(a + b);
Why did you explicitly type casted here? And the same applies for all the methods?

2023-08-16 17:21 UTC, MithunSubramani commented on src/assignment1/Program.cs
Please check the linter warnings and fix it.

2023-08-16 17:23 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +        /// the main class which gets the value and do mathematical operation by use of <see cref="Math"/> class.
Summary can be shortened.

2023-08-16 17:25 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +        public static void Main(string[] args)
Please don't implement logics in Main method, try to separate into private chunk methods.

2023-08-16 17:26 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +    internal class Program
Why the `Program` class is `internal`?

2023-08-16 17:27 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +            }
Avoid nested if-else.

2023-08-16 17:32 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +            if (int.TryParse(Console.ReadLine(), out int a))
Do some more input validation, 
```c#
if (int.TryParse(Console.ReadLine(), out int a))
``` 
You can do something more than this validation.

2023-08-16 17:38 UTC, MithunSubramani commented on src/assignment1/MathUtils.cs
> +        /// <returns> long </returns>
Please check the typos in all the comments.

2023-08-16 17:44 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +                    MathUtils math = new MathUtils();
Can you change this class to static, Is there any reason to create object instance?

2023-08-17 08:02 UTC, MithunSubramani requested changes

2023-08-18 03:37 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +                    if (b != 0)
I explored on console.ReadKey() method and I used in mathutils class program

2023-08-18 03:42 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        }
I tried hard and I reduced some of the nested if-else but I can not able to remove one last nested if-else.

2023-08-18 03:44 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +                    MathUtils math = new MathUtils();
sorry, there is no specific reason to create instance object. So, I have changed the class to static. Thank you : )

2023-08-18 03:46 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +            if (int.TryParse(Console.ReadLine(), out int a))
I am really sorry to say that I can't able to avoid this. I tried my best to avoid this in my next project. once again sorry for that. : (

2023-08-18 03:50 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        {
sure bro, I did this in Mathutils assignment. Without a doubt, I could follow this in all my up coming assignments

2023-08-18 03:50 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        /// the main class which gets the value and do mathematical operation by use of <see cref="Math"/> class.
sure bro, I did this in Mathutils assignment. Without a doubt, I could follow this in all my up coming assignments

2023-08-18 03:55 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +    internal class Program
This internal is the default template which is given by the L&D Team. so, if it is necessary to remove that, tell me, definitely  I will bro.

2023-08-18 03:55 UTC, shafiq005-solin commented on src/assignment1/Program.cs
I fixed all the warning and bugs in the mathUtils program bro.

2023-08-18 04:02 UTC, shafiq005-solin commented on src/assignment1/MathUtils.cs
> +            return (long)(a - b);
If the value of both the input is maximum value of a integer then, the result may have the possibility to get beyond the integer limit. So, i type casted the integer to long to avoid this case.

2023-08-18 04:08 UTC, shafiq005-solin commented on src/assignment1/MathUtils.cs
> +        /// <returns> long </returns>
sorry for some careless mistake. I have rectified the typos and I ensure that I avoid this for the up coming assignments.

2023-08-21 17:09 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +        }
You can reduce this else block by inverting the if case used for checking division by zero.
```c#
                if (b != 0)
                {
                    Console.WriteLine($"Division : {MathUtils.Division(a, b)}");
                }
                else
                {
                    Console.WriteLine($"{a} can not be divided by 0");
                }
```

2023-08-21 17:18 UTC, MithunSubramani requested changes

2023-08-21 17:18 UTC, MithunSubramani commented on src/assignment1/Program.cs
> +        private static void MathMethod()
Please update the method name with a meaningful name.
```suggestion
        private static void ArithmeticOperations()
```

2023-08-21 17:21 UTC, MithunSubramani requested changes

2023-08-21 17:21 UTC, MithunSubramani commented on src/assignment1/MathUtils.cs
> +    public static class MathUtils
Can you please rename this class?

2023-08-22 04:20 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        private static void MathMethod()
MathMethod() is renamed to MathOperations and it is moved to MathUtils class

2023-08-22 04:21 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        private static void MathMethod()
MathMethod method is renamed to "MathOperations".

2023-08-22 04:37 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        }
This if case is moved to a new method called CheckAndDivide()

2023-08-22 04:39 UTC, shafiq005-solin commented on src/assignment1/Program.cs
> +        {
exception handling is added in the main menu

2023-08-22 11:01 UTC, MithunSubramani approved these changes

2023-08-22 11:01 UTC, merged