Feat assignment8 memory management
shafiq005-solin/CSharp-Assignments pull request #10
Opened 2023-09-04 12:29 UTC by shafiq005-solin

# Description
This assignment is help us to learn about the memory organization and how it works. And what are the memories available and how it is organized and how to manage the memory with high efficiency. The concept of Garbage collection and Idisposable. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [x] New and existing unit tests pass locally with my changes

2023-09-27 19:14 UTC, MithunSubramani requested changes

2023-09-27 19:14 UTC, MithunSubramani commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +        /// Colse all the open files
check the typo.

2023-09-27 19:14 UTC, MithunSubramani commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +                StreamReader fileReader = new StreamReader(@"D:\CSharp-Assignments\src\assignment-8\IDisposableDemo\File.txt");
use relative path.

2023-09-27 19:14 UTC, MithunSubramani commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +                string content = fileReader.ReadLine() !;
Any reason to use null forgiving operator?

2023-09-27 19:14 UTC, MithunSubramani commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +                this._fileWriter = new StreamWriter(@"D:\CSharp-Assignments\src\assignment-8\IDisposableDemo\File.txt");
Why it the file is been closed here and file write instance is created?

2023-09-28 09:20 UTC, shafiq005-solin commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +        /// Colse all the open files
typos were fixed.

2023-09-28 09:27 UTC, shafiq005-solin commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +                string content = fileReader.ReadLine() !;
null forgiving operator removed.

2023-09-28 09:32 UTC, shafiq005-solin commented on src/assignment-8/IDisposableDemo/FileManager.cs
> +                this._fileWriter = new StreamWriter(@"D:\CSharp-Assignments\src\assignment-8\IDisposableDemo\File.txt");
If a Class is a child of I Disposable and objected were create in using block then, at the end of the using block it automatically call the Dispose method. To close the opened file automatically we have to keep the file open. That is the only reason to keep that open.

2023-09-29 03:14 UTC, MithunSubramani approved these changes

2023-09-29 04:04 UTC, merged