Feat assignment9 error handling
shafiq005-solin/CSharp-Assignments pull request #11
Opened 2023-09-05 12:02 UTC by shafiq005-solin

# Description
In this assignment, there is a method called divide which will divide the given two integer and returns the quotent value. it also throw Exception when the any value is divided by zero (In other words, Divisor is zero). That error catch in the Interface method. And another method will give the respective elements from the array. It has the possibility to throw Exceptions. And we have to create a custom exception and use that in the respective place. The unhandled exceptions also displayed using a method.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [x] New and existing unit tests pass locally with my changes

2023-09-25 18:17 UTC, MithunSubramani requested changes

2023-09-25 18:17 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +            try
use a single `try` block and `catch` the corresponding errors separately and then use `finally` block.

```c#
try
{
  //operation
}
catch(InputErrorException ex)
{
  //handle exception
}
catch(DivideByZeroException ex)
{
  //handle exception
}
catch(Exception ex)
{
//  handle exception
}
```

2023-09-25 18:17 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +                int value = Operations.IntegerArray(index);
```suggestion
                int value = IntegerArray(index);
```

2023-09-25 18:17 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +        public static int IntegerArray(int index)
Please rename with some valid method name.

2023-09-25 18:17 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +        }
Please check the assignment question, go with that flow. (We can discuss regarding this offline)

2023-09-25 18:17 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +            catch (Exception ex)
No need of this general exception, please do catch specific parsing exceptions.

2023-09-25 18:17 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +        public static int Divide(int a, int b)
This method should return floating number, right?

2023-09-26 14:26 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +                divisor = Operations.GetValidInteger("Enter Divisor : ");
Operations were removed

2023-09-26 14:26 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +            try
single try catch block were implemented

2023-09-26 14:26 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +                int value = Operations.IntegerArray(index);
Operations were removed

2023-09-26 14:27 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +        }
In assignment tells that to add the changes in the same solution which is used in the task one

2023-09-26 14:27 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +            catch (Exception ex)
General exception were changed

2023-09-26 14:28 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +        public static int Divide(int a, int b)
To throw exception, it should return in int. That is the only reason to have that.

2023-09-26 14:29 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +        public static int IntegerArray(int index)
Method name was changed to CreateIntegerArray

2023-09-27 18:02 UTC, MithunSubramani requested changes

2023-09-27 18:02 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +                Console.WriteLine("Division Operation is successfully completed!!");
I think the message in the finally block is not well suited for the action.

2023-09-27 18:02 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +        }
Try to optimize this logic

2023-09-27 18:02 UTC, MithunSubramani commented on src/ErrorHandling/readme.md
Update the readme file with the updated method names

2023-09-27 18:06 UTC, MithunSubramani requested changes

2023-09-27 18:06 UTC, MithunSubramani commented on src/ErrorHandling/Operations.cs
> +                dividend = GetValidInteger("Enter Divident : ");
```suggestion
                dividend = GetValidInteger("Enter Dividend : ");
```

2023-09-28 09:38 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +                Console.WriteLine("Division Operation is successfully completed!!");
Content in finally were changed

2023-09-28 09:44 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +        }
program optimized

2023-09-28 09:45 UTC, shafiq005-solin commented on src/ErrorHandling/Operations.cs
> +                dividend = GetValidInteger("Enter Divident : ");
typos were fixed

2023-09-29 03:27 UTC, MithunSubramani approved these changes

2023-09-29 04:06 UTC, merged