Feat assignmnet16 idisposableanddisposepattern
shafiq005-solin/CSharp-Assignments pull request #22
Opened 2023-10-18 04:52 UTC by shafiq005-solin

# Description
This assignment is for the understanding of the managed and unmanaged resources and how the I Disposable were helping in the unmanaged resources. Why dispose method is used compare to the finalizer.

# How Has This Been Tested?

- [x] Managed resources
- [x] Unmanaged resources

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [x] New and existing unit tests pass locally with my changes

2023-12-05 18:36 UTC, MithunSubramani requested changes

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/ManagedResource.cs
> +    /// Manages the Resources with primary methods
Remove unwanted capitalization in all occurences.

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/UnManagedResource.cs
> +        private static bool IsDisposed { get; set; } = false;
private variable should be at the top of the class  and should start with underscore.

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/UnManagedResource.cs
> +        private static bool IsDisposed { get; set; } = false;
false should be updated in constructor, right?

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/ManagedResource.cs
> +            IsDisposed = true;
Pass it as a parameter to dispose method

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/Program.cs
> +            Fn();
Rename it to a meaningful name.

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/Program.cs
> +            unManaged1.WriteToFile("Anny");
Clean up the code

2023-12-05 18:36 UTC, MithunSubramani commented on src/Assignment-16/IDisposableAndDisposePattern/readme.md
Rephrase the document removing the pronouns

2023-12-05 18:36 UTC, MithunSubramani commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
> +            Assert.Equal(list, managedResource.Data);
```suggestion
            List<string> list = new List<string>();
            list.Add("one");
            
            ManagedResource managedResource = new ManagedResource();
            managedResource.AddData("one");

            Assert.Equal(list, managedResource.Data);
```

2023-12-05 18:36 UTC, MithunSubramani commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
> +            string actual = reader.ReadToEnd();
`actual??` Please update the variable name

2023-12-05 18:36 UTC, MithunSubramani commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
> +        public void Input_AddDate_InputAddedInList()
```suggestion
        public void Input_AddData_InputAddedInList()
```

2023-12-05 18:36 UTC, MithunSubramani commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
Add failure test cases too.

2023-12-05 18:36 UTC, MithunSubramani commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
Rename the test file name.

2023-12-06 06:23 UTC, shafiq005-solin commented on src/Assignment-16/IDisposableAndDisposePattern/ManagedResource.cs
> +    /// Manages the Resources with primary methods
All the unwanted capitalization were removed.

2023-12-06 06:29 UTC, shafiq005-solin commented on src/Assignment-16/IDisposableAndDisposePattern/UnManagedResource.cs
> +        private static bool IsDisposed { get; set; } = false;
The template shows error when we use an underscore in private property. It is a static variable so, there is no need to initialize this variable in constructor.

2023-12-06 06:32 UTC, shafiq005-solin commented on src/Assignment-16/IDisposableAndDisposePattern/ManagedResource.cs
> +            IsDisposed = true;
Parameter was passed to the method.

2023-12-06 06:34 UTC, shafiq005-solin commented on src/Assignment-16/IDisposableAndDisposePattern/Program.cs
> +            unManaged1.WriteToFile("Anny");
This set of code is directly copied from the question, we have to ensure that this set of code should work as excepted. And I add some extra comments in the code to understand easier.

2023-12-06 06:34 UTC, shafiq005-solin commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
> +            Assert.Equal(list, managedResource.Data);
format updated

2023-12-06 06:36 UTC, shafiq005-solin commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
> +            string actual = reader.ReadToEnd();
Variable name were changed

2023-12-06 06:37 UTC, shafiq005-solin commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
> +        public void Input_AddDate_InputAddedInList()
Method name were updated.

2023-12-06 06:40 UTC, shafiq005-solin commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
Failure test cases also added.

2023-12-06 06:41 UTC, shafiq005-solin commented on tests/unit/Assignment-16/IDisposableAndDisposePatternTests/UnitTest1.cs
Test file name was renamed.

2023-12-06 06:52 UTC, shafiq005-solin commented on src/Assignment-16/IDisposableAndDisposePattern/readme.md
The document was rephrased.

2023-12-06 09:18 UTC, MithunSubramani approved these changes

2023-12-06 12:56 UTC, merged