Feat assignment2 contact app
shafiq005-solin/CSharp-Assignments pull request #3
Opened 2023-08-18 05:08 UTC by shafiq005-solin

This app is used to store a persons data like a contact app. It can able to store name of the person, contact number (phone number) of the person, Email ID of the person and some description of the person. We can also do some operation on the contact which is stored already added or stored. like search operation, edit contact, delete contact, etc., There are two different classes used to construct this contact app, they are Main class and Contact class. The main class is base class of this contact app. And it create object of the contact class to store the person's data.

2023-08-21 18:44 UTC, MithunSubramani requested changes

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Contact.cs
> +    public class Contact
Please rename the class.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        public static void NumericChoice(int userInputInt)
Move the Contact operations to separate class.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Contact.cs
> +        public bool IsEquals(string search)
Move this function to the separate class where you will be adding contact manipulation methods.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        public static bool GetFlag()
Move this method too.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +            Regex reg = new Regex(@"^\d+$");
Use separate regular expressions for each fields, like validating the email formats `xyz@gmail.com`, restricting digits of mobile, restricting characters in description, name.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +            Console.WriteLine("welcome!!");
Move this to separate class.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        public static bool GetFlag()
Add proper description to this method. At first, I cannot understand the method without reading the whole code.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                if (userInput != null)
Remove nested if condition.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Contact.cs
> +        public bool IsEquals(string search)
Model class should be separate, and other manipulating operations should be in separate class according to the usage.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        /// <param name="userInput">choise string</param>
Correct the typo `choise -> choice` everywhere.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        public static void StringChoise(string userInput)
Use enum classes instead of plain string.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                        StringChoise(userInput);
You have enabled string based choice selection, but in user perspective, You displayed input instructions based on integer only. Please update the instructions which should be flexible for both type of inputs.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                        foreach (var obj in _contactList)
```suggestion
                        foreach (var contact in _contactList)
``` 
Variable name should be meaningful as per the usage.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                        foreach (var obj in _contactList)
```suggestion
                        foreach (var contact in _contactList)
```
update variable name

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                foreach (var obj in _contactList)
update variable name.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +            Console.WriteLine("Enter name : ");
Use `Console.Write` instead, so that input read will be in the same line.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                Console.WriteLine("Only numerics!!..");
Add meaningful prompt messages.

2023-08-21 18:44 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        public static void EditContact()
Please add the same validation to edit method also. (suggestion: Create a validation class separately and move all validation logics there)

2023-08-21 18:52 UTC, MithunSubramani requested changes

2023-08-21 18:52 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                Console.Clear();
```c#
                Console.Clear();
                Console.WriteLine("===========================================================");
                Console.WriteLine("there are six operation here");
                Console.Write("1.Enter new contact  ");
                Console.Write("2.search contact  ");
                Console.Write("3.Edit  ");
                Console.Write("4.Delete  ");
                Console.Write("5.View all  ");
                Console.WriteLine("6.exit");
                Console.WriteLine("choose any one to work on : ");
``` 
Convert these lines to a single line.

2023-08-21 18:52 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                        Console.Clear();
Can move the `Console.Clear()` to the top the switch case, so that duplicate line of codes can be reduced.

2023-08-22 06:44 UTC, shafiq005-solin commented on src/Assignment-2/Contact.cs
> +    public class Contact
Class "Contact" is renamed to "ContactManager"

2023-08-22 06:45 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        public static void NumericChoice(int userInputInt)
All the contact operations are moved to a separate class named "ContactOperations".

2023-08-22 06:50 UTC, shafiq005-solin commented on src/Assignment-2/Contact.cs
> +        public bool IsEquals(string search)
IsEquals method is moved to ContactOperations class.

2023-08-22 06:51 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        public static bool GetFlag()
I removed the method because it is not required.

2023-08-22 07:10 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +            Regex reg = new Regex(@"^\d+$");
I added regular expression for email and name of the person.

2023-08-22 07:14 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                foreach (var obj in _contactList)
variable name was updated.

2023-08-22 07:15 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +            Console.WriteLine("Enter name : ");
console.writeLine() was replaced by console.Write() method.

2023-08-22 07:27 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                Console.WriteLine("Only numerics!!..");
meaningful prompts are added

2023-08-22 08:10 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        public static void EditContact()
I combined all the regex validation into one method.

2023-08-22 08:13 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                Console.Clear();
I converted all those lines into two lines

2023-08-22 08:14 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                        Console.Clear();
That console.clear() is moved to the top of the switch case.

2023-08-22 08:26 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +            Console.WriteLine("welcome!!");
that set of code is moved to a separate method

2023-08-22 08:44 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        public static bool GetFlag()
proper descriptions are added to all the methods and classes

2023-08-22 08:44 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                if (userInput != null)
most of the nested if-else are removed

2023-08-22 08:46 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        /// <param name="userInput">choise string</param>
all typos are fixed

2023-08-22 08:52 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                        StringChoise(userInput);
instructions are updated

2023-08-22 09:29 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        public static void StringChoise(string userInput)
enum was added instead of plain strings

2023-08-24 05:34 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +            Regex reg = new Regex(@"^\d+$");
Adding separate regular expressions for name and email is fine, look into restricting the size of the values.

2023-08-24 05:41 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +                        StringChoise(userInput);
User Information is not clear to me still, can you please update to more understandable format?

2023-08-24 05:47 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +        public static void EditContact()
Can you please move that to a separate validator class, to make the code more readable?

2023-08-24 06:21 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +            Regex reg = new Regex(@"^\d+$");
size validation is also added

2023-08-24 06:21 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +        public static void EditContact()
Validator class is created and validations methods are added to that class

2023-08-24 06:35 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                        StringChoise(userInput);
Additional information is added for user understanding.

2023-08-24 15:31 UTC, MithunSubramani requested changes

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +            Console.WriteLine("The six operations are listed below");
Explore on `Verbatim string literals` to log using a single `Console.Writeline`.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactManager.cs
> +        /// Gets or Sets the Name of the person
Please make the description more crisp.
```suggestion
        /// Name of the person
```
Do change in all the occurrences also.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperationHandler.cs
> +        public static void NumericChoice(int userInputInt, List<ContactManager> contactList)
```suggestion
        public static void NumericMenuHandler(int userInputInt, List<ContactManager> contactList)
```

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperationHandler.cs
> +        public static void Stringchoice(string userInput, List<ContactManager> contactList)
You can combine both numeric-based and string-based menu selection, as Enum is used.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperationHandler.cs
> +                        foreach (var obj in contactList)
```suggestion
                        foreach (var contact in contactList)
```

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperationHandler.cs
> +                        foreach (var obj in contactList)
```suggestion
                        foreach (var contact in contactList)
```

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +    using System.Text.RegularExpressions;
Why import statement is inside the namespace?

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +            Console.WriteLine("Sucssfully created!! ");
Fix the typo.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +            string note = Validator.GetValidInput();
Add max limit for description field too.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +                        editList[id - 1].Name = Validator.GetRegexMatchedString(@"^[a-z]{2}[a-z]+.*");
Use a variable.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/Program.cs
> +            Console.WriteLine("welcome To contact manager app :) \n\n");
Please reframe this sentence.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/Validator.cs
> +    using System.Text.RegularExpressions;
Move the import statement out of namespace.

2023-08-24 15:31 UTC, MithunSubramani commented on src/Assignment-2/Validator.cs
> +            while (regName.IsMatch(input) == false)
```suggestion
            while (!regName.IsMatch(input))
```

2023-08-25 03:46 UTC, shafiq005-solin commented on src/Assignment-2/ContactManager.cs
> +        /// Gets or Sets the Name of the person
Actually it was the template bro, if I try to remove the "Gets or Sets" it shows warning to add "Gets or Sets" in the beginning of the line.

2023-08-25 03:50 UTC, shafiq005-solin commented on src/Assignment-2/Validator.cs
> +    using System.Text.RegularExpressions;
This is also in part of template. If I move it out of the namespace, it shows warning for that

2023-08-25 03:58 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperationHandler.cs
> +        public static void NumericChoice(int userInputInt, List<ContactManager> contactList)
Name of the methods are successfully changed

2023-08-25 04:00 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperationHandler.cs
> +        public static void Stringchoice(string userInput, List<ContactManager> contactList)
Enum is used in both the menu Selections method

2023-08-25 04:02 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperationHandler.cs
> +                        foreach (var obj in contactList)
Name of the variable is changed to contact

2023-08-25 04:02 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +    Console.WriteLine(e.Message);
indentation was fixed

2023-08-25 04:03 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +                    }
Enum is used in both the menu Selections method

2023-08-25 04:05 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +            Console.WriteLine("welcome To contact manager app :) \n\n");
sentence reframed

2023-08-25 04:07 UTC, shafiq005-solin commented on src/Assignment-2/Validator.cs
> +            while (regName.IsMatch(input) == false)
while loop condition is changed

2023-08-25 04:27 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +            Console.WriteLine("The six operations are listed below");
I explored on Verbatim string literals. And I reduced most of the console.WriteLine()

2023-08-28 04:15 UTC, shafiq005-solin commented on src/Assignment-2/Program.cs
> +    using System.Text.RegularExpressions;
This is also in part of template. If I move it out of the namespace, it shows warning for that

2023-08-28 04:15 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +    using System.Text.RegularExpressions;
This is also in part of template. If I move it out of the namespace, it shows warning for that

2023-08-28 04:15 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +            Console.WriteLine("Sucssfully created!! ");
typos are fixed

2023-08-28 04:15 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +            string note = Validator.GetValidInput();
Max limit is also added for validation

2023-08-28 04:16 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +            ContactManager contact = new ContactManager(name, phone, email, note);
All occurrences are changed

2023-08-28 04:16 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperationHandler.cs
> +                        foreach (var obj in contactList)
variable name is changed to contact

2023-08-28 04:17 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +                        editList[id - 1].Name = Validator.GetRegexMatchedString(@"^[a-z]{2}[a-z]+.*");
A separate variable is used

2023-08-28 05:36 UTC, MithunSubramani requested changes

2023-08-28 05:36 UTC, MithunSubramani commented on src/Assignment-2/ContactOperationHandler.cs
> +        public static void NumericMenuHandler(int userInputInt, List<ContactManager> contactList)
Try to merge numeric and string menu handlers

2023-08-28 05:36 UTC, MithunSubramani commented on src/Assignment-2/ContactOperationHandler.cs
> +                        Console.WriteLine($"{count} results found");
Move this to a private method.

2023-08-28 05:36 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +                {
Make this private.

2023-08-28 05:36 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +                case "1":
Support string based selection, if possible

2023-08-28 05:36 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +                        editList[id - 1].Name = name;
make this separate variable

2023-08-28 05:39 UTC, MithunSubramani requested changes

2023-08-28 05:39 UTC, MithunSubramani commented on src/Assignment-2/ContactOperations.cs
> +            while (name.Length > 30);
Do this validation within regex itself.

2023-08-28 06:11 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +                        editList[id - 1].Name = Validator.GetRegexMatchedString(@"^[a-z]{2}[a-z]+.*");
separate variable is used as EditContact

2023-08-28 06:13 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperationHandler.cs
> +        public static void NumericMenuHandler(int userInputInt, List<ContactManager> contactList)
both menu method is merged into a single menu method

2023-08-28 06:13 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperationHandler.cs
> +                        Console.WriteLine($"{count} results found");
those statements are moved to a new method

2023-08-28 06:15 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +                case "1":
strings are also supported for choice

2023-08-28 06:15 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +                        editList[id - 1].Name = name;
separate variable is used as EditContact

2023-08-28 06:16 UTC, shafiq005-solin commented on src/Assignment-2/ContactOperations.cs
> +            while (name.Length > 30);
This validation is added in the regex itself

2023-08-30 05:51 UTC, MithunSubramani approved these changes

2023-08-30 06:10 UTC, merged