Feat assignment5 oops exercise
shafiq005-solin/CSharp-Assignments pull request #7
Opened 2023-08-24 04:25 UTC by shafiq005-solin

# Description

In this assignment, there is parent abstract class which has some properties, methods and some abstract methods. And there are two different classes which are child class of the Parent class. Those classes will override the parent class methods. And create some new functionalities to the methods. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [x] New and existing unit tests pass locally with my changes

2023-09-06 04:00 UTC, MithunSubramani requested changes

2023-09-06 04:00 UTC, MithunSubramani commented on src/assignment-5/BankingSystem/SavingAccount.cs
> +            if ((this.Balance - amount) < MINIMUMBALANCE)
Will it be ok, if you pass remaining balance as a parameter to the virtual method?

2023-09-06 06:04 UTC, shafiq005-solin commented on src/assignment-5/ShapeHierarchy/Circle.cs
> +            return (int)(this.Radius * 2 * 3.14f);
Area was converted into float

2023-09-06 06:05 UTC, shafiq005-solin commented on src/assignment-5/ShapeHierarchy/Circle.cs
> +            Console.WriteLine($"\n\n\t\tCircle\nRadius : {this.Radius}");
Unit was included for both

2023-09-06 06:06 UTC, shafiq005-solin commented on src/assignment-5/EmployeeHierarchy/ValidInput.cs
Name was converted into ValidateInput.cs

2023-09-06 06:10 UTC, shafiq005-solin commented on src/assignment-5/EmployeeHierarchy/Employee.cs
> +        public int Salary { get; set; }
Salary converted into Decimal

2023-09-06 06:11 UTC, shafiq005-solin commented on src/assignment-5/ShapeHierarchy/Program.cs
> +                        Console.Write("\t\t Rectangle\nEnter Length : ");
Code moved to a private method

2023-09-06 06:12 UTC, shafiq005-solin commented on src/assignment-5/ShapeHierarchy/Program.cs
> +                        Console.Write("\t\t Circle\nEnter Radius : ");
I tried but I couldn't. It is quite complex to do that.

2023-09-06 06:13 UTC, shafiq005-solin commented on src/assignment-5/EmployeeHierarchy/Manager.cs
> +            Console.WriteLine($"Position  : Manager");
This was in the given assignment. We should override the method in the child class

2023-09-06 06:14 UTC, shafiq005-solin commented on src/assignment-5/EmployeeHierarchy/Program.cs
> +                        Console.Write("\t\t Manager\nEnter Name : ");
These code was moved to another private method

2023-09-06 06:14 UTC, shafiq005-solin commented on src/assignment-5/EmployeeHierarchy/Program.cs
> +                        break;
I tried but I couldn't. It is quite complex to do that.

2023-09-06 06:14 UTC, shafiq005-solin commented on src/assignment-5/ShapeHierarchy/ValidInput.cs
Name was changed to ValidateInput.cs

2023-09-06 06:15 UTC, shafiq005-solin commented on src/assignment-5/ShapeHierarchy/ValidInput.cs
New project was created as Utilities for all validations

2023-09-06 06:16 UTC, shafiq005-solin commented on src/assignment-5/BankingSystem/BankAccount.cs
> +            if (this.Balance - amount > -1)
converted to zero

2023-09-06 06:17 UTC, shafiq005-solin commented on src/assignment-5/BankingSystem/SavingAccount.cs
> +            if ((this.Balance - amount) < MINIMUMBALANCE)
Code was changed now, it is not needed there.

2023-09-07 04:16 UTC, MithunSubramani requested changes

2023-09-07 04:16 UTC, MithunSubramani commented on src/assignment-5/Utilities/ValidateInput.cs
> +        /// <summary>
Can you merge the `GetValidDecimal` and `GetValidInteger` methods, if possible.

2023-09-07 04:16 UTC, MithunSubramani commented on src/assignment-5/Utilities/Program.cs
Is `Program.cs` needed?

2023-09-07 06:44 UTC, shafiq005-solin commented on src/assignment-5/Utilities/Program.cs
Without Program.cs It is not working as excepted

2023-09-07 06:45 UTC, shafiq005-solin commented on src/assignment-5/Utilities/ValidateInput.cs
> +        /// <summary>
Both methods were merged and make into a single method

2023-09-08 06:31 UTC, MithunSubramani approved these changes

2023-09-08 06:31 UTC, MithunSubramani commented on src/assignment-5/BankingSystem/Operations.cs
> +            int choice = Utilities.ValidateInput.GetValidinput<int>();
Import `Utilities' and use.

2023-09-08 06:45 UTC, shafiq005-solin commented on src/assignment-5/BankingSystem/Operations.cs
> +            int choice = Utilities.ValidateInput.GetValidinput<int>();
Utilities class imported.

2023-09-12 09:02 UTC, merged