Feat assignment7 memory optimization
shafiq005-solin/CSharp-Assignments pull request #9
Opened 2023-08-31 05:11 UTC by shafiq005-solin

# Description

In this assignment,  Exploration of memory management is completed, a critical aspect of any high-performance application. Detecting, diagnosing, and resolving memory issues in a C# codebase. Understanding the usage tools for memory profiling.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [x] New and existing unit tests pass locally with my changes

2023-09-13 16:14 UTC, MithunSubramani requested changes

2023-09-13 16:14 UTC, MithunSubramani commented on src/assignment-7/README.md
Please explain the changes in code and also explain how it optimizes the memory.

2023-09-14 04:23 UTC, shafiq005-solin commented on src/assignment-7/README.md
Explanation added to the readme file

2023-09-15 03:44 UTC, MithunSubramani approved these changes

2023-09-15 05:06 UTC, merged